version: '2.3'

#launch all the containers for the f1tenth simulation
services: 
  #create a rosmaster so that all containers can talk to each other properly
  rosmaster: 
    image: ros_test
    build: .
    container_name: rosmaster
    command: /bin/bash -c 'source devel/setup.bash && roscore'
#launch the f1tenth container and display the gazebo simulation using nvidia drivers
  f1tenth:
    image: ros_test
    build: .
    container_name: f1tenth
    runtime: nvidia
    #make sure that this container is started after the rosmaster by using the depends clause
    depends_on:
      - "rosmaster"
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - "ROS_HOSTNAME=f1tenth"
      - "ROS_MASTER_URI=http://rosmaster:11311" 
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ros-logs:/root/.ros/
      - ./a_stars_pure_pursuit:/home/catkin_ws/src/a_stars_pure_pursuit
      - gazebo-files:/root/.gazebo/
    command: /bin/bash -c 'source devel/setup.bash && roslaunch wall_following docker.launch'
  
  rviz:
    image: ros_test
    build: .
    container_name: rviz
    runtime: nvidia
    depends_on:
      - "rosmaster"
      - "f1tenth"
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - "ROS_HOSTNAME=rviz"
      - "ROS_MASTER_URI=http://rosmaster:11311" 
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./a_stars_pure_pursuit:/home/catkin_ws/src/a_stars_pure_pursuit
    command: /bin/bash -c 'source devel/setup.bash && roslaunch race docker_rviz.launch'
  
  #launch keyboard node
  keyboard: 
    image: ros_test
    build: .
    container_name: keyboard
    depends_on: 
      - "rosmaster"
      - "f1tenth"
    stdin_open: true
    tty: true
    environment:
      - "ROS_HOSTNAME=keyboard"
      - "ROS_MASTER_URI=http://rosmaster:11311"
    command: /bin/bash -c 'source devel/setup.bash && bash' #&& rosrun race keyboard.py'
  
volumes:
  ros-logs:
  gazebo-files:
